//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1.ISWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISWebService.ISWebServiceSoap")]
    public interface ISWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Lab1.ISWebService.HelloWorldResponse HelloWorld(Lab1.ISWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.HelloWorldResponse> HelloWorldAsync(Lab1.ISWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name _manufacturer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountByManufacturer", ReplyAction="*")]
        Lab1.ISWebService.CountByManufacturerResponse CountByManufacturer(Lab1.ISWebService.CountByManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountByManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.CountByManufacturerResponse> CountByManufacturerAsync(Lab1.ISWebService.CountByManufacturerRequest request);
        
        // CODEGEN: Generating message contract since element name _resolution from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountByResolution", ReplyAction="*")]
        Lab1.ISWebService.CountByResolutionResponse CountByResolution(Lab1.ISWebService.CountByResolutionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountByResolution", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.CountByResolutionResponse> CountByResolutionAsync(Lab1.ISWebService.CountByResolutionRequest request);
        
        // CODEGEN: Generating message contract since element name GetResolutionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResolutions", ReplyAction="*")]
        Lab1.ISWebService.GetResolutionsResponse GetResolutions(Lab1.ISWebService.GetResolutionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResolutions", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.GetResolutionsResponse> GetResolutionsAsync(Lab1.ISWebService.GetResolutionsRequest request);
        
        // CODEGEN: Generating message contract since element name GetColumnNamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnNames", ReplyAction="*")]
        Lab1.ISWebService.GetColumnNamesResponse GetColumnNames(Lab1.ISWebService.GetColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.GetColumnNamesResponse> GetColumnNamesAsync(Lab1.ISWebService.GetColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name _columns from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportToXML", ReplyAction="*")]
        Lab1.ISWebService.ExportToXMLResponse ExportToXML(Lab1.ISWebService.ExportToXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportToXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1.ISWebService.ExportToXMLResponse> ExportToXMLAsync(Lab1.ISWebService.ExportToXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab1.ISWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab1.ISWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountByManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountByManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.CountByManufacturerRequestBody Body;
        
        public CountByManufacturerRequest() {
        }
        
        public CountByManufacturerRequest(Lab1.ISWebService.CountByManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountByManufacturerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _manufacturer;
        
        public CountByManufacturerRequestBody() {
        }
        
        public CountByManufacturerRequestBody(string _manufacturer) {
            this._manufacturer = _manufacturer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountByManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountByManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.CountByManufacturerResponseBody Body;
        
        public CountByManufacturerResponse() {
        }
        
        public CountByManufacturerResponse(Lab1.ISWebService.CountByManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountByManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountByManufacturerResult;
        
        public CountByManufacturerResponseBody() {
        }
        
        public CountByManufacturerResponseBody(int CountByManufacturerResult) {
            this.CountByManufacturerResult = CountByManufacturerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountByResolutionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountByResolution", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.CountByResolutionRequestBody Body;
        
        public CountByResolutionRequest() {
        }
        
        public CountByResolutionRequest(Lab1.ISWebService.CountByResolutionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountByResolutionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _resolution;
        
        public CountByResolutionRequestBody() {
        }
        
        public CountByResolutionRequestBody(string _resolution) {
            this._resolution = _resolution;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountByResolutionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountByResolutionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.CountByResolutionResponseBody Body;
        
        public CountByResolutionResponse() {
        }
        
        public CountByResolutionResponse(Lab1.ISWebService.CountByResolutionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountByResolutionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountByResolutionResult;
        
        public CountByResolutionResponseBody() {
        }
        
        public CountByResolutionResponseBody(int CountByResolutionResult) {
            this.CountByResolutionResult = CountByResolutionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResolutionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResolutions", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.GetResolutionsRequestBody Body;
        
        public GetResolutionsRequest() {
        }
        
        public GetResolutionsRequest(Lab1.ISWebService.GetResolutionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetResolutionsRequestBody {
        
        public GetResolutionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResolutionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResolutionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.GetResolutionsResponseBody Body;
        
        public GetResolutionsResponse() {
        }
        
        public GetResolutionsResponse(Lab1.ISWebService.GetResolutionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResolutionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab1.ISWebService.ArrayOfString GetResolutionsResult;
        
        public GetResolutionsResponseBody() {
        }
        
        public GetResolutionsResponseBody(Lab1.ISWebService.ArrayOfString GetResolutionsResult) {
            this.GetResolutionsResult = GetResolutionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnNames", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.GetColumnNamesRequestBody Body;
        
        public GetColumnNamesRequest() {
        }
        
        public GetColumnNamesRequest(Lab1.ISWebService.GetColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnNamesRequestBody {
        
        public GetColumnNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.GetColumnNamesResponseBody Body;
        
        public GetColumnNamesResponse() {
        }
        
        public GetColumnNamesResponse(Lab1.ISWebService.GetColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab1.ISWebService.ArrayOfString GetColumnNamesResult;
        
        public GetColumnNamesResponseBody() {
        }
        
        public GetColumnNamesResponseBody(Lab1.ISWebService.ArrayOfString GetColumnNamesResult) {
            this.GetColumnNamesResult = GetColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportToXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportToXML", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.ExportToXMLRequestBody Body;
        
        public ExportToXMLRequest() {
        }
        
        public ExportToXMLRequest(Lab1.ISWebService.ExportToXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExportToXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab1.ISWebService.ArrayOfString _columns;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _fileName;
        
        public ExportToXMLRequestBody() {
        }
        
        public ExportToXMLRequestBody(Lab1.ISWebService.ArrayOfString _columns, string _fileName) {
            this._columns = _columns;
            this._fileName = _fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportToXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportToXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1.ISWebService.ExportToXMLResponseBody Body;
        
        public ExportToXMLResponse() {
        }
        
        public ExportToXMLResponse(Lab1.ISWebService.ExportToXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExportToXMLResponseBody {
        
        public ExportToXMLResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWebServiceSoapChannel : Lab1.ISWebService.ISWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWebServiceSoapClient : System.ServiceModel.ClientBase<Lab1.ISWebService.ISWebServiceSoap>, Lab1.ISWebService.ISWebServiceSoap {
        
        public SWebServiceSoapClient() {
        }
        
        public SWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.HelloWorldResponse Lab1.ISWebService.ISWebServiceSoap.HelloWorld(Lab1.ISWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab1.ISWebService.HelloWorldRequest inValue = new Lab1.ISWebService.HelloWorldRequest();
            inValue.Body = new Lab1.ISWebService.HelloWorldRequestBody();
            Lab1.ISWebService.HelloWorldResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.HelloWorldResponse> Lab1.ISWebService.ISWebServiceSoap.HelloWorldAsync(Lab1.ISWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.HelloWorldResponse> HelloWorldAsync() {
            Lab1.ISWebService.HelloWorldRequest inValue = new Lab1.ISWebService.HelloWorldRequest();
            inValue.Body = new Lab1.ISWebService.HelloWorldRequestBody();
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.CountByManufacturerResponse Lab1.ISWebService.ISWebServiceSoap.CountByManufacturer(Lab1.ISWebService.CountByManufacturerRequest request) {
            return base.Channel.CountByManufacturer(request);
        }
        
        public int CountByManufacturer(string _manufacturer) {
            Lab1.ISWebService.CountByManufacturerRequest inValue = new Lab1.ISWebService.CountByManufacturerRequest();
            inValue.Body = new Lab1.ISWebService.CountByManufacturerRequestBody();
            inValue.Body._manufacturer = _manufacturer;
            Lab1.ISWebService.CountByManufacturerResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).CountByManufacturer(inValue);
            return retVal.Body.CountByManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.CountByManufacturerResponse> Lab1.ISWebService.ISWebServiceSoap.CountByManufacturerAsync(Lab1.ISWebService.CountByManufacturerRequest request) {
            return base.Channel.CountByManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.CountByManufacturerResponse> CountByManufacturerAsync(string _manufacturer) {
            Lab1.ISWebService.CountByManufacturerRequest inValue = new Lab1.ISWebService.CountByManufacturerRequest();
            inValue.Body = new Lab1.ISWebService.CountByManufacturerRequestBody();
            inValue.Body._manufacturer = _manufacturer;
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).CountByManufacturerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.CountByResolutionResponse Lab1.ISWebService.ISWebServiceSoap.CountByResolution(Lab1.ISWebService.CountByResolutionRequest request) {
            return base.Channel.CountByResolution(request);
        }
        
        public int CountByResolution(string _resolution) {
            Lab1.ISWebService.CountByResolutionRequest inValue = new Lab1.ISWebService.CountByResolutionRequest();
            inValue.Body = new Lab1.ISWebService.CountByResolutionRequestBody();
            inValue.Body._resolution = _resolution;
            Lab1.ISWebService.CountByResolutionResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).CountByResolution(inValue);
            return retVal.Body.CountByResolutionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.CountByResolutionResponse> Lab1.ISWebService.ISWebServiceSoap.CountByResolutionAsync(Lab1.ISWebService.CountByResolutionRequest request) {
            return base.Channel.CountByResolutionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.CountByResolutionResponse> CountByResolutionAsync(string _resolution) {
            Lab1.ISWebService.CountByResolutionRequest inValue = new Lab1.ISWebService.CountByResolutionRequest();
            inValue.Body = new Lab1.ISWebService.CountByResolutionRequestBody();
            inValue.Body._resolution = _resolution;
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).CountByResolutionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.GetResolutionsResponse Lab1.ISWebService.ISWebServiceSoap.GetResolutions(Lab1.ISWebService.GetResolutionsRequest request) {
            return base.Channel.GetResolutions(request);
        }
        
        public Lab1.ISWebService.ArrayOfString GetResolutions() {
            Lab1.ISWebService.GetResolutionsRequest inValue = new Lab1.ISWebService.GetResolutionsRequest();
            inValue.Body = new Lab1.ISWebService.GetResolutionsRequestBody();
            Lab1.ISWebService.GetResolutionsResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).GetResolutions(inValue);
            return retVal.Body.GetResolutionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.GetResolutionsResponse> Lab1.ISWebService.ISWebServiceSoap.GetResolutionsAsync(Lab1.ISWebService.GetResolutionsRequest request) {
            return base.Channel.GetResolutionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.GetResolutionsResponse> GetResolutionsAsync() {
            Lab1.ISWebService.GetResolutionsRequest inValue = new Lab1.ISWebService.GetResolutionsRequest();
            inValue.Body = new Lab1.ISWebService.GetResolutionsRequestBody();
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).GetResolutionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.GetColumnNamesResponse Lab1.ISWebService.ISWebServiceSoap.GetColumnNames(Lab1.ISWebService.GetColumnNamesRequest request) {
            return base.Channel.GetColumnNames(request);
        }
        
        public Lab1.ISWebService.ArrayOfString GetColumnNames() {
            Lab1.ISWebService.GetColumnNamesRequest inValue = new Lab1.ISWebService.GetColumnNamesRequest();
            inValue.Body = new Lab1.ISWebService.GetColumnNamesRequestBody();
            Lab1.ISWebService.GetColumnNamesResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).GetColumnNames(inValue);
            return retVal.Body.GetColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.GetColumnNamesResponse> Lab1.ISWebService.ISWebServiceSoap.GetColumnNamesAsync(Lab1.ISWebService.GetColumnNamesRequest request) {
            return base.Channel.GetColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.GetColumnNamesResponse> GetColumnNamesAsync() {
            Lab1.ISWebService.GetColumnNamesRequest inValue = new Lab1.ISWebService.GetColumnNamesRequest();
            inValue.Body = new Lab1.ISWebService.GetColumnNamesRequestBody();
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).GetColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1.ISWebService.ExportToXMLResponse Lab1.ISWebService.ISWebServiceSoap.ExportToXML(Lab1.ISWebService.ExportToXMLRequest request) {
            return base.Channel.ExportToXML(request);
        }
        
        public void ExportToXML(Lab1.ISWebService.ArrayOfString _columns, string _fileName) {
            Lab1.ISWebService.ExportToXMLRequest inValue = new Lab1.ISWebService.ExportToXMLRequest();
            inValue.Body = new Lab1.ISWebService.ExportToXMLRequestBody();
            inValue.Body._columns = _columns;
            inValue.Body._fileName = _fileName;
            Lab1.ISWebService.ExportToXMLResponse retVal = ((Lab1.ISWebService.ISWebServiceSoap)(this)).ExportToXML(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1.ISWebService.ExportToXMLResponse> Lab1.ISWebService.ISWebServiceSoap.ExportToXMLAsync(Lab1.ISWebService.ExportToXMLRequest request) {
            return base.Channel.ExportToXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1.ISWebService.ExportToXMLResponse> ExportToXMLAsync(Lab1.ISWebService.ArrayOfString _columns, string _fileName) {
            Lab1.ISWebService.ExportToXMLRequest inValue = new Lab1.ISWebService.ExportToXMLRequest();
            inValue.Body = new Lab1.ISWebService.ExportToXMLRequestBody();
            inValue.Body._columns = _columns;
            inValue.Body._fileName = _fileName;
            return ((Lab1.ISWebService.ISWebServiceSoap)(this)).ExportToXMLAsync(inValue);
        }
    }
}
